name: dl_env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  # Core PyTorch libs with CUDA 12.4 support
  - matplotlib
  - pandas
  - pip:
    # Any specific pip-only packages
    - pytorch
    - tqdm
    - ipykernel
