name: hw4
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    # The -f flag tells pip where to find the specific CUDA wheels
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    # The -i flag forces the Tsinghua mirror for the standard packages
    - --index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
    
    # Core GPU Libraries
    - torch==1.8.0+cu111
    - torchvision==0.9.0+cu111
    - torchaudio==0.8.0
    - torchtext==0.9.0
    - nltk
    - numpy
    - matplotlib
    - tqdm
    - prettytable
    - black